# Generated by Django 4.1.7 on 2026-07-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resume_ats_breakdown_resume_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
